language: node_js
node_js:
  - "0.10"

env:
  global:
    - SAUCE_USERNAME=ariatemplates
    - SAUCE_ACCESS_KEY=620e638e-90d2-48e1-b66c-f9505dcb888b
    - secure: bGENSGZguDwxsHJu9JyEggr0KhNd9l/RguvlS4zknMV32Hujtt60tsD9X9IKRIO96Fv4loDburOco38SdzezVzd6AS/wsxJsoqD//C2+BXJKzU4MsGXeqS5hx6r2CiTWCnDoIu2QvyK9qiO+Gu0VII76//3pa50m7EVYT79jVxM=

before_install:
 - npm install --quiet -g grunt-cli

before_script:
 - curl https://gist.githubusercontent.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

script:
 - grunt ci

after_success:
 - chmod -R 777 ./ci-release.sh
 - ./ci-release.sh